### ISSUE TITLE
build error under Espressif esp-idf

### ISSUE THREAD

**Issue by driftregion** [SimonCahill/isotp-c#83]
Hi Simon, 

Thanks for isotp-c.  I noticed a new build error after bumping the isotp-c version to 1.9.3 in iso14229.

I build examples for a handful of embedded platforms using their default build configurations, and this issue only surfaced on the ESP32 example.
By default, Espressif's esp-idf invokes a fork of gcc with many warnings promoted to errors, including `-Wstringop-overflow`, which triggers here.

```sh
/home/njames/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20260121/riscv32-esp-elf/bin/riscv32-esp-elf-gcc --version
riscv32-esp-elf-gcc (crosstool-NG esp-14.2.0_20260121) 14.2.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

/home/njames/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20260121/riscv32-esp-elf/bin/riscv32-esp-elf-gcc \
  -Isrc/tp/isotp-c \
  -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable \
  -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations \
  -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion \
  -Og -std=gnu17 -Wno-old-style-declaration \
  -c src/tp/isotp-c/isotp.c -o /tmp/isotp_only.o
src/tp/isotp-c/isotp.c: In function 'isotp_send_single_frame':
src/tp/isotp-c/isotp.c:181:15: error: 'memcpy' writing 8 or more bytes into a region of size 6 overflows the destination [-Werror=stringop-overflow=]
  181 |         (void)memcpy(message.as.single_frame_escape.data, link->send_buffer, link->send_size);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/tp/isotp-c/isotp.c:160:21: note: at offset 2 into destination object 'message' of size 8
  160 |     IsoTpCanMessage message;
      |                     ^~~~~~~
cc1: some warnings being treated as errors
```

I found that Espressif has documentation describing this very issue:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/gcc.html#wstringop-overflow-wstringop-overread-wstringop-truncation-and-warray-bounds

but they suggest sprinkling pragmas around the line, which kind of sucks.

An alternative is this code, which satisfies the compiler
```c
        uint32_t copy_size = link->send_size;
        if (copy_size > sizeof(message.as.single_frame_escape.data)) {
            copy_size = sizeof(message.as.single_frame_escape.data);
        }
        assert(copy_size == link->send_size);
        (void)memcpy(message.as.single_frame_escape.data, link->send_buffer, copy_size);
```

Also, searching around shows that this behavior is not confined to Espressif's fork and exists in upstream gcc generally, but I wasn't able to reproduce it with the gcc 13.3.0 on my machine.

```sh
gcc --version
gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


gcc -Isrc/tp/isotp-c \
  -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable \
  -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations \
  -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion \
  -Og -std=gnu17 -Wno-old-style-declaration \
  -c src/tp/isotp-c/isotp.c -o /tmp/isotp_native.o
```

**Comment by SimonCahill** [comment]
Hi Nick!

Thanks for reporting!
I generally don't use GCC much any more, in favour of clang, but the CI pipelines in this repo generally use both GCC and clang.

I'm currently writing some more CI tests for different embedded platforms to see if I can repro the issue.
The change to the code seems simple enough. I haven't done any RISC-V development so far, so that was also not on my radar. Lemme see what I find :)
